drivers_root = /Lightning-Fire-Data-Uden-2026/model_drivers
rds_root = /Lightning-Fire-Data-Uden-2026/rds
table_root = /Lightning-Fire-Data-Uden-2026/model_performance
predictions_root = /Lightning-Fire-Data-Uden-2026/model_predictions
figure_root = /path/to/wherever/you/want/to/put/figures
data_root = /Lightning-Fire-Data-Uden-2026/other_data 
netcdf_root = /unprocessed/ERA5/climate/data/must/be/downloaded/
landcover_root = /unprocessed/landcover/must/be/downloaded/